import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, FetchedValue, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class AuditLog(Base):
    """New table (US-013-db-design.md), write target for this story's own
    two new event types only, per staged OD-14. No FK on `actor_id`/
    `target_id` — must survive account erasure (BR-007/AU-AC8), matching
    every existing audit table's precedent.

    Daily range-partitioning and the `BEFORE INSERT` hash-chain trigger are
    hand-written DDL in migration T3b, not expressed here — SQLAlchemy has
    no dialect-level construct for `PARTITION BY RANGE`, which is exactly
    why that migration is hand-written rather than autogenerated. `(id,
    occurred_at)` is a composite primary key because PostgreSQL requires
    the partition key to be part of every unique constraint on a
    partitioned table.
    """

    __tablename__ = "audit_log"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), primary_key=True, nullable=False, server_default=func.now()
    )
    category: Mapped[str] = mapped_column(String(32), nullable=False)
    actor_id: Mapped[uuid.UUID | None] = mapped_column()
    actor_role: Mapped[str | None] = mapped_column(String(32))
    event: Mapped[str] = mapped_column(String(64), nullable=False)
    target_id: Mapped[uuid.UUID | None] = mapped_column()
    outcome: Mapped[str | None] = mapped_column(String(32))
    request_id: Mapped[str | None] = mapped_column(String(64))
    ip: Mapped[str | None] = mapped_column(String(45))
    user_agent: Mapped[str | None] = mapped_column(Text())
    # First JSONB column in this codebase (prior precedent, roles/models.py,
    # only uses postgresql.ARRAY) — noted here since db-design.md's own
    # entity model didn't flag it as a new pattern.
    payload: Mapped[dict[str, Any] | None] = mapped_column(JSONB())
    # Trigger-computed (migration T3b's BEFORE INSERT trigger) — never set
    # by application code. `FetchedValue()` tells SQLAlchemy the value comes
    # from the server: it's omitted from the INSERT and the attribute is
    # marked for fetch-on-access, letting the trigger populate a genuinely
    # NOT NULL column before the constraint is checked.
    previous_hash: Mapped[str] = mapped_column(
        String(64), nullable=False, server_default=FetchedValue()
    )
    row_hash: Mapped[str] = mapped_column(String(64), nullable=False, server_default=FetchedValue())
