import asyncio
from logging.config import fileConfig
from typing import Any

from alembic import context
from alembic.autogenerate import rewriter
from alembic.operations import ops
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from app.core.config import get_settings
from app.db.base import Base
from app.modules.account import models as account_models  # noqa: F401  # registers models
from app.modules.admin_users import models as admin_users_models  # noqa: F401  # registers models
from app.modules.audit import models as audit_models  # noqa: F401  # registers models
from app.modules.email_verification import (  # noqa: F401  # registers models with Base
    models as email_verification_models,
)
from app.modules.profile import models as profile_models  # noqa: F401  # registers models
from app.modules.roles import models as roles_models  # noqa: F401  # registers models
from app.modules.support import models as support_models  # noqa: F401  # registers models
from app.modules.users import models as users_models  # noqa: F401  # registers User with Base

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = Base.metadata

# Autogenerate always emits bare create/drop directives. This rewriter injects
# if_not_exists/if_exists into them so upgrade/downgrade/upgrade cycles and
# reruns against a partially-applied schema don't hard-fail. It only reaches
# autogenerated ops — hand-written op.execute()/raw SQL/data backfills in a
# migration still need their own sa.inspect() guards.
#
# The two callbacks below are the sole exemption from the "no Any" rule: the
# Rewriter dispatches by runtime type across multiple unrelated op classes
# (table vs. index), and alembic's own callback signature is untyped upstream.
process_revision_directives = rewriter.Rewriter()


@process_revision_directives.rewrites(ops.CreateTableOp)
@process_revision_directives.rewrites(ops.CreateIndexOp)
def _add_if_not_exists(context: Any, revision: Any, op: Any) -> Any:
    op.if_not_exists = True
    return op


@process_revision_directives.rewrites(ops.DropTableOp)
@process_revision_directives.rewrites(ops.DropIndexOp)
def _add_if_exists(context: Any, revision: Any, op: Any) -> Any:
    op.if_exists = True
    return op


# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        process_revision_directives=process_revision_directives,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        process_revision_directives=process_revision_directives,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """In this scenario we need to create an Engine
    and associate a connection with the context.

    """

    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""

    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
