"""add_login_audit_and_refresh_tokens

Revision ID: 1cdc08e88be9
Revises: 7e371ad49a0a
Create Date: 2026-08-31 20:40:13.450696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cdc08e88be9"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "7e371ad49a0a"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_auth_audit_log_actor_id"),
        "auth_audit_log",
        ["actor_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"),
        "refresh_tokens",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    # NOTE: autogenerate also proposed dropping 'account_lifecycle_audit_log'
    # (and its index) here. That is a false positive caused by a pre-existing
    # gap in migrations/env.py: it never imports app.modules.account.models,
    # so that table has been invisible to Base.metadata (and therefore to
    # autogenerate's diff) since US-004 added it. Removed by hand — this
    # story's models.py never touched that table, and migrations/env.py is
    # protected (AGENTS.md §7.9), so the real fix needs explicit user
    # sign-off rather than being made here.
    # The Rewriter in migrations/env.py only reaches autogenerated
    # Create/DropTableOp and Create/DropIndexOp; add_column/drop_column need
    # their own guard so upgrade/downgrade/upgrade cycles stay idempotent.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {column["name"] for column in inspector.get_columns("users")}
    if "last_login_at" not in columns:
        op.add_column(
            "users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {column["name"] for column in inspector.get_columns("users")}
    if "last_login_at" in columns:
        op.drop_column("users", "last_login_at")
    # NOTE: account_lifecycle_audit_log's recreation was removed here too —
    # see the matching NOTE in upgrade(). It was never dropped, so it must
    # not be recreated.
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens", if_exists=True)
    op.drop_table("refresh_tokens", if_exists=True)
    op.drop_index(op.f("ix_auth_audit_log_actor_id"), table_name="auth_audit_log", if_exists=True)
    op.drop_table("auth_audit_log", if_exists=True)
    # ### end Alembic commands ###
