"""add_ticket_resolution_columns

Revision ID: 242e0dba5ba2
Revises: 9132a68b73c8
Create Date: 2026-09-05 22:26:56.933204

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "242e0dba5ba2"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "9132a68b73c8"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Autogenerate's raw diff also proposed dropping and (on downgrade)
# re-creating `audit_log_default` and seven indexes
# (`ix_account_lifecycle_audit_log_occurred_at`, `ix_admin_audit_log_occurred_at`,
# `ix_audit_log_occurred_at_actor_id_event`, `ix_auth_audit_log_occurred_at`,
# `ix_profile_audit_log_timestamp`, `ix_users_display_name_trgm`,
# `ix_users_email_trgm`) - all created via hand-written `op.execute()` DDL in
# prior migrations with no matching SQLAlchemy construct for autogenerate to
# compare against, so it saw them as "not in the model" and proposed removing
# them. None of this is in this story's scope; stripped from both
# `upgrade()`/`downgrade()` below, the same precedent
# `9132a68b73c8_add_ticket_replies.py` already set for the identical noise.

_CHECK_CLOSED_FIELDS = "ck_tickets_closed_requires_closed_fields"
_CHECK_RESOLVED_FIELDS = "ck_tickets_resolved_requires_resolution_fields"


def upgrade() -> None:
    """Upgrade schema."""
    # The Rewriter in migrations/env.py only reaches autogenerated
    # Create/DropTableOp and Create/DropIndexOp; add_column and
    # create_check_constraint need their own guard, matching
    # 2c77dd65027b's/9132a68b73c8's add_column guard pattern.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    ticket_columns = {c["name"] for c in inspector.get_columns("tickets")}
    if "resolved_at" not in ticket_columns:
        op.add_column(
            "tickets", sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True)
        )
    if "resolution_note" not in ticket_columns:
        op.add_column(
            "tickets", sa.Column("resolution_note", sa.String(length=5000), nullable=True)
        )
    if "closed_at" not in ticket_columns:
        op.add_column("tickets", sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True))
    if "closed_by" not in ticket_columns:
        op.add_column("tickets", sa.Column("closed_by", sa.Uuid(), nullable=True))

    op.create_index(
        "ix_tickets_resolved_at_pending_autoclose",
        "tickets",
        ["resolved_at"],
        unique=False,
        postgresql_where=sa.text("status = 'resolved'"),
        if_not_exists=True,
    )

    ticket_checks = {c["name"] for c in inspector.get_check_constraints("tickets")}
    if _CHECK_CLOSED_FIELDS not in ticket_checks:
        op.create_check_constraint(
            _CHECK_CLOSED_FIELDS,
            "tickets",
            "(status = 'closed') = (closed_at IS NOT NULL AND closed_by IS NOT NULL)",
        )
    if _CHECK_RESOLVED_FIELDS not in ticket_checks:
        op.create_check_constraint(
            _CHECK_RESOLVED_FIELDS,
            "tickets",
            "status != 'resolved' OR (resolved_at IS NOT NULL AND resolution_note IS NOT NULL)",
        )


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    ticket_checks = {c["name"] for c in inspector.get_check_constraints("tickets")}
    if _CHECK_RESOLVED_FIELDS in ticket_checks:
        op.drop_constraint(_CHECK_RESOLVED_FIELDS, "tickets", type_="check")
    if _CHECK_CLOSED_FIELDS in ticket_checks:
        op.drop_constraint(_CHECK_CLOSED_FIELDS, "tickets", type_="check")

    op.drop_index(
        "ix_tickets_resolved_at_pending_autoclose",
        table_name="tickets",
        postgresql_where=sa.text("status = 'resolved'"),
        if_exists=True,
    )

    ticket_columns = {c["name"] for c in inspector.get_columns("tickets")}
    if "closed_by" in ticket_columns:
        op.drop_column("tickets", "closed_by")
    if "closed_at" in ticket_columns:
        op.drop_column("tickets", "closed_at")
    if "resolution_note" in ticket_columns:
        op.drop_column("tickets", "resolution_note")
    if "resolved_at" in ticket_columns:
        op.drop_column("tickets", "resolved_at")
