"""add profile and auth foundation

Revision ID: 2c77dd65027b
Revises: 430aa1b298fb
Create Date: 2026-08-29 22:48:57.688395

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c77dd65027b"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "430aa1b298fb"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_AUDIT_LOG_GUARD_FUNCTION = "profile_audit_log_deny_mutation"


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "profile_audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_table(
        "email_change_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
        if_not_exists=True,
    )
    op.create_index(
        "ix_email_change_tokens_user_id",
        "email_change_tokens",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table(
        "user_sessions",
        sa.Column("jti", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("jti"),
        if_not_exists=True,
    )
    op.create_index(
        "ix_user_sessions_user_id", "user_sessions", ["user_id"], unique=False, if_not_exists=True
    )

    # The Rewriter in migrations/env.py only reaches autogenerated
    # Create/DropTableOp and Create/DropIndexOp; add_column/drop_column need
    # their own guard so upgrade/downgrade/upgrade cycles stay idempotent.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {column["name"] for column in inspector.get_columns("users")}
    if "display_name" not in columns:
        op.add_column("users", sa.Column("display_name", sa.String(length=255), nullable=True))
    if "locale" not in columns:
        op.add_column("users", sa.Column("locale", sa.String(length=35), nullable=True))
    if "timezone" not in columns:
        op.add_column("users", sa.Column("timezone", sa.String(length=64), nullable=True))
    if "avatar_url" not in columns:
        op.add_column("users", sa.Column("avatar_url", sa.String(length=2048), nullable=True))
    if "pending_email" not in columns:
        op.add_column("users", sa.Column("pending_email", sa.String(length=320), nullable=True))

    # profile_audit_log is append-only per NFR-005: no UPDATE/DELETE, enforced
    # at the DB layer via a trigger (autogenerate/the Rewriter can't reach
    # hand-written DDL, so this is guarded with CREATE OR REPLACE / IF NOT
    # EXISTS directly, matching AGENTS.md's op.execute() guard requirement).
    op.execute(
        f"""
        CREATE OR REPLACE FUNCTION {_AUDIT_LOG_GUARD_FUNCTION}()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'profile_audit_log is append-only: % is not permitted', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute("DROP TRIGGER IF EXISTS profile_audit_log_no_update_delete ON profile_audit_log;")
    op.execute(
        f"""
        CREATE TRIGGER profile_audit_log_no_update_delete
        BEFORE UPDATE OR DELETE ON profile_audit_log
        FOR EACH ROW EXECUTE FUNCTION {_AUDIT_LOG_GUARD_FUNCTION}();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS profile_audit_log_no_update_delete ON profile_audit_log;")
    op.execute(f"DROP FUNCTION IF EXISTS {_AUDIT_LOG_GUARD_FUNCTION}();")

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {column["name"] for column in inspector.get_columns("users")}
    if "pending_email" in columns:
        op.drop_column("users", "pending_email")
    if "avatar_url" in columns:
        op.drop_column("users", "avatar_url")
    if "timezone" in columns:
        op.drop_column("users", "timezone")
    if "locale" in columns:
        op.drop_column("users", "locale")
    if "display_name" in columns:
        op.drop_column("users", "display_name")

    op.drop_index("ix_user_sessions_user_id", table_name="user_sessions", if_exists=True)
    op.drop_table("user_sessions", if_exists=True)
    op.drop_index(
        "ix_email_change_tokens_user_id", table_name="email_change_tokens", if_exists=True
    )
    op.drop_table("email_change_tokens", if_exists=True)
    op.drop_table("profile_audit_log", if_exists=True)
