"""add_support_tickets

Revision ID: 37c89e98a86f
Revises: 5dd6fff75016
Create Date: 2026-09-03 15:57:40.857068

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37c89e98a86f"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "5dd6fff75016"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Autogenerate's raw diff also proposed dropping and (on downgrade)
# re-creating `audit_log_default` (a hash-partition child table) and five
# indexes (`ix_account_lifecycle_audit_log_occurred_at`,
# `ix_admin_audit_log_occurred_at`, `ix_audit_log_occurred_at_actor_id_event`,
# `ix_auth_audit_log_occurred_at`, `ix_profile_audit_log_timestamp`,
# `ix_users_display_name_trgm`, `ix_users_email_trgm`) — all created via
# hand-written `op.execute()` DDL in prior migrations (57a978462b74,
# 1b2b1d52dd71) with no matching SQLAlchemy `Table()`/`Index()` declaration
# for autogenerate to compare against, so it saw them as "not in the model"
# and proposed removing them. None of this is in this story's scope; those
# lines are stripped from both `upgrade()` and `downgrade()` below,
# consistent with `migrations/versions/2c77dd65027b_...py`'s own precedent of
# hand-editing an autogenerated diff down to only the intended change.

# `ticket_number` (FR-1) is server-computed - a hand-written PostgreSQL
# `SEQUENCE` plus a column `DEFAULT` expression, formatted
# `CP-{year}-{seq:07d}` - which autogenerate cannot produce (no SQLAlchemy
# construct models `SEQUENCE`-backed string formatting). Both statements are
# idempotent at the SQL level (`IF NOT EXISTS`, and `SET DEFAULT` is
# naturally idempotent - reapplying it is a no-op), matching
# 57a978462b74's own idempotent-raw-DDL precedent; no `sa.inspect()` guard is
# layered on top for the same reason that migration didn't need one.
_CREATE_SEQUENCE = "CREATE SEQUENCE IF NOT EXISTS ticket_number_seq"
_SET_TICKET_NUMBER_DEFAULT = (
    "ALTER TABLE tickets ALTER COLUMN ticket_number "
    "SET DEFAULT 'CP-' || extract(year from now()) || '-' || "
    "lpad(nextval('ticket_number_seq')::text, 7, '0')"
)
_DROP_TICKET_NUMBER_DEFAULT = "ALTER TABLE tickets ALTER COLUMN ticket_number DROP DEFAULT"
_DROP_SEQUENCE = "DROP SEQUENCE IF EXISTS ticket_number_seq"


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "ticket_number", sa.String(length=20), server_default=sa.FetchedValue(), nullable=False
        ),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.String(length=150), nullable=False),
        sa.Column("body", sa.String(length=5000), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="open", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticket_number"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_tickets_requester_id"),
        "tickets",
        ["requester_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_tickets_requester_id_created_at_id",
        "tickets",
        ["requester_id", "created_at", "id"],
        unique=False,
        if_not_exists=True,
    )
    op.execute(_CREATE_SEQUENCE)
    op.execute(_SET_TICKET_NUMBER_DEFAULT)
    op.create_table(
        "attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        "ix_attachments_created_at_unbound",
        "attachments",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("ticket_id IS NULL"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_attachments_ticket_id"),
        "attachments",
        ["ticket_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_attachments_uploaded_by"),
        "attachments",
        ["uploaded_by"],
        unique=False,
        if_not_exists=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_attachments_uploaded_by"), table_name="attachments", if_exists=True)
    op.drop_index(op.f("ix_attachments_ticket_id"), table_name="attachments", if_exists=True)
    op.drop_index(
        "ix_attachments_created_at_unbound",
        table_name="attachments",
        postgresql_where=sa.text("ticket_id IS NULL"),
        if_exists=True,
    )
    op.drop_table("attachments", if_exists=True)
    op.execute(_DROP_TICKET_NUMBER_DEFAULT)
    op.execute(_DROP_SEQUENCE)
    op.drop_index("ix_tickets_requester_id_created_at_id", table_name="tickets", if_exists=True)
    op.drop_index(op.f("ix_tickets_requester_id"), table_name="tickets", if_exists=True)
    op.drop_table("tickets", if_exists=True)
