"""add_ticket_assignee_column

Revision ID: 55d8d34a9753
Revises: 242e0dba5ba2
Create Date: 2026-09-07 20:39:21.987980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55d8d34a9753"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "242e0dba5ba2"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Autogenerate's raw diff also proposed dropping and (on downgrade)
# re-creating `audit_log_default` and seven indexes
# (`ix_account_lifecycle_audit_log_occurred_at`, `ix_admin_audit_log_occurred_at`,
# `ix_audit_log_occurred_at_actor_id_event`, `ix_auth_audit_log_occurred_at`,
# `ix_profile_audit_log_timestamp`, `ix_users_display_name_trgm`,
# `ix_users_email_trgm`) - all created via hand-written `op.execute()` DDL in
# prior migrations with no matching SQLAlchemy construct for autogenerate to
# compare against, so it saw them as "not in the model" and proposed removing
# them. None of this is in this story's scope; stripped from both
# `upgrade()`/`downgrade()` below, the same precedent `242e0dba5ba2_...py`/
# `9132a68b73c8_...py` already set for the identical noise.

# `tickets.assignee_id`'s FK needs an explicit name: autogenerate left it
# unnamed (`create_foreign_key(None, ...)`), which only works because no
# `naming_convention` is registered on `Base.metadata` (app/db/base.py) -
# PostgreSQL's own default constraint-naming convention is used explicitly
# here so `downgrade()` can name it back (same precedent as
# `9132a68b73c8`'s `_ATTACHMENTS_TICKET_REPLY_ID_FK`).
_TICKETS_ASSIGNEE_ID_FK = "tickets_assignee_id_fkey"


def upgrade() -> None:
    """Upgrade schema."""
    # The Rewriter in migrations/env.py only reaches autogenerated
    # Create/DropTableOp and Create/DropIndexOp; add_column/create_foreign_key
    # need their own guard so upgrade/downgrade/upgrade cycles stay
    # idempotent, matching 242e0dba5ba2's/9132a68b73c8's add_column guard
    # pattern.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    ticket_columns = {c["name"] for c in inspector.get_columns("tickets")}
    if "assignee_id" not in ticket_columns:
        op.add_column("tickets", sa.Column("assignee_id", sa.Uuid(), nullable=True))

    # US-4.4 FR-1 (AQ-AC1): the default, filterless agent queue partial
    # index. Predicate MUST be the literal `status != 'closed'` (never
    # `.in_([...])`) - PostgreSQL's partial-index predicate-implication check
    # reliably proves a `<>` comparison but not a semantically-equivalent
    # `IN`-list (US-4.4-db-design.md "Indexes").
    op.create_index(
        "ix_tickets_queue_default_updated_at_id",
        "tickets",
        ["updated_at", "id"],
        unique=False,
        postgresql_where=sa.text("status != 'closed'"),
        if_not_exists=True,
    )
    # US-4.4 FR-2 (AQ-AC2): an explicit status=X filter, any of the five
    # values including "closed".
    op.create_index(
        "ix_tickets_status_updated_at_id",
        "tickets",
        ["status", "updated_at", "id"],
        unique=False,
        if_not_exists=True,
    )
    # US-4.4 FR-2: assignee_id=<uuid>/assignee_id=me (equality) and
    # assignee_id=none (IS NULL - a btree index serves this directly).
    op.create_index(
        "ix_tickets_assignee_id_updated_at_id",
        "tickets",
        ["assignee_id", "updated_at", "id"],
        unique=False,
        if_not_exists=True,
    )

    ticket_fks = {fk["name"] for fk in inspector.get_foreign_keys("tickets")}
    if _TICKETS_ASSIGNEE_ID_FK not in ticket_fks:
        op.create_foreign_key(
            _TICKETS_ASSIGNEE_ID_FK,
            "tickets",
            "users",
            ["assignee_id"],
            ["id"],
        )


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    ticket_fks = {fk["name"] for fk in inspector.get_foreign_keys("tickets")}
    if _TICKETS_ASSIGNEE_ID_FK in ticket_fks:
        op.drop_constraint(_TICKETS_ASSIGNEE_ID_FK, "tickets", type_="foreignkey")

    op.drop_index("ix_tickets_assignee_id_updated_at_id", table_name="tickets", if_exists=True)
    op.drop_index("ix_tickets_status_updated_at_id", table_name="tickets", if_exists=True)
    op.drop_index(
        "ix_tickets_queue_default_updated_at_id",
        table_name="tickets",
        postgresql_where=sa.text("status != 'closed'"),
        if_exists=True,
    )

    ticket_columns = {c["name"] for c in inspector.get_columns("tickets")}
    if "assignee_id" in ticket_columns:
        op.drop_column("tickets", "assignee_id")
