"""add_audit_log_and_history_view

Revision ID: 57a978462b74
Revises: 81fe406156fa
Create Date: 2026-09-02 15:20:00.000000

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57a978462b74"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "81fe406156fa"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Hand-written raw DDL throughout: SQLAlchemy has no dialect construct for
# `PARTITION BY RANGE`, `BEFORE INSERT` triggers, or plain SQL views, which
# is exactly why this migration is hand-written rather than autogenerated
# (AGENTS.md §4). Every statement below is idempotent at the SQL level
# (`IF NOT EXISTS`, `CREATE OR REPLACE`, or an explicit `DROP ... IF EXISTS`
# before a bare `CREATE`), matching this project's `if_not_exists=True`/
# `CREATE EXTENSION IF NOT EXISTS` precedent (1b2b1d52dd71) — no separate
# `sa.inspect()` guard is needed on top of that.

_CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS audit_log (
    id uuid NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    category varchar(32) NOT NULL,
    actor_id uuid,
    actor_role varchar(32),
    event varchar(64) NOT NULL,
    target_id uuid,
    outcome varchar(32),
    request_id varchar(64),
    ip varchar(45),
    user_agent text,
    payload jsonb,
    previous_hash varchar(64) NOT NULL,
    row_hash varchar(64) NOT NULL,
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at)
"""

# `audit_log_pkey` was already taken by the not-yet-detached
# `unverified_account_purge_log` at the time this table was created (T3
# renames that table but PostgreSQL does not rename its constraints along
# with it) — PostgreSQL auto-suffixes the collision, so this table's PK is
# named `audit_log_pkey1`. Harmless, but a future autogenerate diff or
# re-rename could trip on the mismatch between the table name and its PK
# constraint name; noted here so it isn't mistaken for a migration bug.

# US-3.3 OD-16: no named daily partitions are created by this migration —
# every row lands in DEFAULT until a future, separate partition-provisioning
# job (not part of this story's scope) creates real day partitions ahead of
# time. A partitioned table with only a DEFAULT partition is valid
# PostgreSQL; this is the safety net, not a placeholder for missing scope.
_CREATE_DEFAULT_PARTITION = """
CREATE TABLE IF NOT EXISTS audit_log_default PARTITION OF audit_log DEFAULT
"""

# US-013-entity-model.md's Indexes Summary: covering index for FR-1's
# filtered, newest-first query. Also load-bearing for the hash-chain
# trigger's own seed query (`ORDER BY occurred_at DESC, id DESC LIMIT 1`,
# run on every single INSERT) — without this, that query full-scans and
# sorts the table on every write, degrading as the chain grows (caught by
# advisor at IMPLEMENTATION review, 2026-09-02, after `\\d+ audit_log`
# showed only the composite PK). A plain (non-`CONCURRENTLY`) index is
# correct here: `audit_log` is a brand-new, empty table at migration time,
# unlike the four pre-existing, actively-written tables T3c indexes.
# Created on the partitioned parent — PostgreSQL propagates a parent index
# to every partition, including `DEFAULT` and any created later.
_CREATE_COVERING_INDEX = """
CREATE INDEX IF NOT EXISTS ix_audit_log_occurred_at_actor_id_event
    ON audit_log (occurred_at DESC, actor_id, event)
"""
_DROP_COVERING_INDEX = "DROP INDEX IF EXISTS ix_audit_log_occurred_at_actor_id_event"

# Pure hash computation, deliberately factored out of the trigger function
# so `scripts/verify_audit_chain.py` (T6) can call this *same* function via
# SQL to recompute a row's expected hash, rather than reimplementing the
# concatenation/serialization in Python — `payload`'s `::text` rendering is
# deterministic within one PostgreSQL installation but not something a
# second, independent implementation should have to match by coincidence.
_CREATE_HASH_FUNCTION = """
CREATE OR REPLACE FUNCTION audit_log_row_hash(
    p_previous_hash text,
    p_occurred_at timestamptz,
    p_actor_id uuid,
    p_event text,
    p_target_id uuid,
    p_payload jsonb
) RETURNS text AS $$
    SELECT encode(
        sha256(
            convert_to(
                p_previous_hash || '|' || p_occurred_at::text || '|' ||
                COALESCE(p_actor_id::text, '') || '|' || p_event || '|' ||
                COALESCE(p_target_id::text, '') || '|' || COALESCE(p_payload::text, ''),
                'UTF8'
            )
        ),
        'hex'
    )
$$ LANGUAGE sql IMMUTABLE
"""

# OD-6 (concurrent-insert correctness, resolved 2026-09-02 at IMPLEMENTATION
# stage): a plain `SELECT ... ORDER BY ... LIMIT 1 FOR UPDATE` on the prior
# row does NOT serialize concurrent appends — the row it locks is never
# itself modified, so a second transaction's blocked lock request is
# granted, once the first commits, with no re-check of which row is now
# the true chain tail (no EvalPlanQual trigger, since the locked row's
# xmin never moved). Two concurrent inserts would both seed from the same
# stale `previous_hash` — the exact false-positive break AU-AC7's own gate
# test would then report. `pg_advisory_xact_lock` fixes this: it serializes
# every `audit_log` insert on one constant key for the life of the
# transaction, auto-released on commit or rollback, no unlock path to get
# wrong. Under staged OD-14 this is two low-frequency event types on one
# admin route — an acceptable cost; a future OD-14 follow-up repointing a
# high-volume module (e.g. auth) into this same chain would need to
# revisit whether one global lock still scales.
#
# OD-17 (genesis rule, resolved 2026-09-02): the seed query has no `WHERE`
# predicate and no `FOR UPDATE` — it always reads the chain's actual most
# recent row (`ORDER BY occurred_at DESC, id DESC LIMIT 1`), skipping
# empty days implicitly (an empty day simply has no row to be "most
# recent"). A `WHERE occurred_at <= NEW.occurred_at` predicate was
# considered and rejected: the `DEFAULT` partition (OD-16) accepts
# out-of-order/backdated `occurred_at` values, and that predicate would
# seed a backdated insert from a stale mid-chain row, fabricating a break
# that isn't tampering. The very first row ever inserted has no prior row
# at all (`v_prev_hash IS NULL`); it seeds from the fixed sentinel, the
# hex-encoded SHA-256 of the empty string.
_CREATE_TRIGGER_FUNCTION = """
CREATE OR REPLACE FUNCTION audit_log_hash_chain() RETURNS trigger AS $$
DECLARE
    v_prev_hash text;
BEGIN
    PERFORM pg_advisory_xact_lock(hashtext('audit_log_hash_chain'));

    SELECT row_hash INTO v_prev_hash
    FROM audit_log
    ORDER BY occurred_at DESC, id DESC
    LIMIT 1;

    IF v_prev_hash IS NULL THEN
        v_prev_hash := encode(sha256(''::bytea), 'hex');
    END IF;

    NEW.previous_hash := v_prev_hash;
    NEW.row_hash := audit_log_row_hash(
        v_prev_hash, NEW.occurred_at, NEW.actor_id, NEW.event, NEW.target_id, NEW.payload
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql
"""

# No `CREATE TRIGGER IF NOT EXISTS` in PostgreSQL — `DROP ... IF EXISTS`
# first makes the pair idempotent on a rerun. Defined on the partitioned
# parent: PostgreSQL clones a parent's row-level `BEFORE INSERT` trigger to
# every partition, including ones created later by a future partition-
# provisioning job, without that job needing to redeclare it.
_DROP_TRIGGER = "DROP TRIGGER IF EXISTS audit_log_hash_chain_trigger ON audit_log"
_CREATE_TRIGGER = """
CREATE TRIGGER audit_log_hash_chain_trigger
    BEFORE INSERT ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_hash_chain()
"""

# Compatibility view over the 4 existing, still-live per-domain tables plus
# `audit_log` itself (US-013-entity-model.md) — `ticket_audit_log` (a 5th
# source) is excluded per OD-4, since Epic 4/the ticket module doesn't
# exist yet; extending this view is a small migration when it ships.
# `profile_audit_log`'s timestamp column is actually named `timestamp`, not
# `occurred_at` (found during T3c prep, correcting this design's own
# column list) — aliased below. Column types are cast/NULLed to match
# `audit_log`'s own projection exactly, since PostgreSQL requires every
# `UNION ALL` branch to agree on column types.
_CREATE_VIEW = """
CREATE OR REPLACE VIEW audit_log_history AS
SELECT id, occurred_at, category, actor_id, actor_role, event, target_id,
       outcome, request_id, ip, user_agent, payload, previous_hash, row_hash
FROM audit_log
UNION ALL
SELECT id, occurred_at, 'auth' AS category, actor_id, NULL::varchar(32) AS actor_role,
       event, NULL::uuid AS target_id, NULL::varchar(32) AS outcome, request_id, ip,
       user_agent, NULL::jsonb AS payload, NULL::varchar(64) AS previous_hash,
       NULL::varchar(64) AS row_hash
FROM auth_audit_log
UNION ALL
SELECT id, occurred_at, 'admin' AS category, actor_id, NULL::varchar(32) AS actor_role,
       event, target_id, NULL::varchar(32) AS outcome, request_id, NULL::varchar(45) AS ip,
       NULL::text AS user_agent, NULL::jsonb AS payload, NULL::varchar(64) AS previous_hash,
       NULL::varchar(64) AS row_hash
FROM admin_audit_log
UNION ALL
SELECT id, "timestamp" AS occurred_at, 'profile' AS category, actor_id,
       NULL::varchar(32) AS actor_role, 'field_changed' AS event, NULL::uuid AS target_id,
       NULL::varchar(32) AS outcome, request_id, NULL::varchar(45) AS ip,
       NULL::text AS user_agent, NULL::jsonb AS payload, NULL::varchar(64) AS previous_hash,
       NULL::varchar(64) AS row_hash
FROM profile_audit_log
UNION ALL
SELECT id, occurred_at, 'account_lifecycle' AS category, NULL::uuid AS actor_id,
       NULL::varchar(32) AS actor_role, event, user_id AS target_id,
       NULL::varchar(32) AS outcome, NULL::varchar(64) AS request_id, NULL::varchar(45) AS ip,
       NULL::text AS user_agent, NULL::jsonb AS payload, NULL::varchar(64) AS previous_hash,
       NULL::varchar(64) AS row_hash
FROM account_lifecycle_audit_log
"""

_DROP_VIEW = "DROP VIEW IF EXISTS audit_log_history"
_DROP_TRIGGER_FUNCTION = "DROP FUNCTION IF EXISTS audit_log_hash_chain()"
_DROP_HASH_FUNCTION = (
    "DROP FUNCTION IF EXISTS audit_log_row_hash(text, timestamptz, uuid, text, uuid, jsonb)"
)
_DROP_DEFAULT_PARTITION = "DROP TABLE IF EXISTS audit_log_default"
_DROP_TABLE = "DROP TABLE IF EXISTS audit_log"


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(_CREATE_TABLE)
    op.execute(_CREATE_DEFAULT_PARTITION)
    op.execute(_CREATE_COVERING_INDEX)
    op.execute(_CREATE_HASH_FUNCTION)
    op.execute(_CREATE_TRIGGER_FUNCTION)
    op.execute(_DROP_TRIGGER)
    op.execute(_CREATE_TRIGGER)
    op.execute(_CREATE_VIEW)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(_DROP_VIEW)
    op.execute(_DROP_TRIGGER)
    op.execute(_DROP_TRIGGER_FUNCTION)
    op.execute(_DROP_HASH_FUNCTION)
    op.execute(_DROP_COVERING_INDEX)
    op.execute(_DROP_DEFAULT_PARTITION)
    op.execute(_DROP_TABLE)
