"""add_occurred_at_indexes

Revision ID: 5dd6fff75016
Revises: 57a978462b74
Create Date: 2026-09-02 15:40:00.000000

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5dd6fff75016"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "57a978462b74"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# US-3.3-entity-model.md: required for `audit_log_history`'s `occurred_at
# DESC` keyset pagination (FR-1) to produce a merge-append instead of
# sorting the full union — none of these 4 tables' existing indexes lead
# with `occurred_at` (verified against the live models). All 4 tables are
# actively written (staged OD-14 keeps them live), so each index is built
# `CONCURRENTLY` — which cannot run inside a transaction, hence this
# migration is alone and every create is wrapped in `autocommit_block()`,
# mirroring db8cbd5e3697/1b2b1d52dd71's identical precedent. Passing
# `if_not_exists=True` directly (as both of those precedents do) is
# sufficient on its own — no separate `sa.inspect()` guard needed; the
# Rewriter only auto-injects that kwarg for autogenerated directives, but
# hand-written code can pass it explicitly itself, which this does.
#
# `profile_audit_log`'s timestamp column is actually named `timestamp`,
# not `occurred_at` (found during T3c prep, correcting db-design.md's own
# column list) — its index name/column reflect that.
_INDEXES = (
    ("ix_auth_audit_log_occurred_at", "auth_audit_log", "occurred_at"),
    ("ix_admin_audit_log_occurred_at", "admin_audit_log", "occurred_at"),
    ("ix_profile_audit_log_timestamp", "profile_audit_log", "timestamp"),
    ("ix_account_lifecycle_audit_log_occurred_at", "account_lifecycle_audit_log", "occurred_at"),
)


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        for index_name, table_name, column_name in _INDEXES:
            op.create_index(
                index_name,
                table_name,
                [column_name],
                unique=False,
                postgresql_concurrently=True,
                if_not_exists=True,
            )


def downgrade() -> None:
    """Downgrade schema."""
    with op.get_context().autocommit_block():
        for index_name, table_name, _ in reversed(_INDEXES):
            op.drop_index(
                index_name,
                table_name=table_name,
                postgresql_concurrently=True,
                if_exists=True,
            )
