"""add account deactivation

Revision ID: 7e371ad49a0a
Revises: 2c77dd65027b
Create Date: 2026-08-30 00:00:00.000000

Hand-authored, not produced by `alembic revision --autogenerate` (no
standalone Postgres was reachable to autogenerate against). The upgrade ->
downgrade -> upgrade proof cycle AGENTS.md SS4 requires was captured instead
via tests/conftest.py's session-scoped fixture, which runs `alembic upgrade
head` against a fresh testcontainer at test-session start and `alembic
downgrade base` at teardown -- verified clean across multiple full pytest
runs (e.g. `Running upgrade 2c77dd65027b -> 7e371ad49a0a, add account
deactivation` then `Running downgrade 7e371ad49a0a -> 2c77dd65027b` with no
errors).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e371ad49a0a"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "2c77dd65027b"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "account_lifecycle_audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        "ix_account_lifecycle_audit_log_user_id",
        "account_lifecycle_audit_log",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )

    # The Rewriter in migrations/env.py only reaches autogenerated
    # Create/DropTableOp and Create/DropIndexOp; add_column/drop_column need
    # their own guard so upgrade/downgrade/upgrade cycles stay idempotent.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {column["name"] for column in inspector.get_columns("users")}
    if "deactivated_at" not in columns:
        op.add_column(
            "users", sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True)
        )


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {column["name"] for column in inspector.get_columns("users")}
    if "deactivated_at" in columns:
        op.drop_column("users", "deactivated_at")

    op.drop_index(
        "ix_account_lifecycle_audit_log_user_id",
        table_name="account_lifecycle_audit_log",
        if_exists=True,
    )
    op.drop_table("account_lifecycle_audit_log", if_exists=True)
