"""rename_email_verification_audit_log

Revision ID: 81fe406156fa
Revises: 1b2b1d52dd71
Create Date: 2026-09-02 15:00:00.000000

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81fe406156fa"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "1b2b1d52dd71"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_NAME = "audit_log"
_NEW_NAME = "unverified_account_purge_log"


def upgrade() -> None:
    """Upgrade schema.

    US-3.3 OD-1: `email_verification`'s pre-existing `audit_log` table
    (BR-002's unverified-account purge job) collides with US-3.3's own new
    `audit_log` table — the two are unrelated. A pure rename via
    `op.rename_table` (not create+drop) preserves every existing row and
    the table's own PK/data unchanged; must land before T3b creates the
    new `audit_log`, or the name stays occupied. `ALTER TABLE ... RENAME`
    is itself idempotent-safe under a bare rerun only in the sense that a
    second run against an already-renamed table fails cleanly (the old
    name no longer exists) rather than silently double-renaming — matches
    this project's other hand-written, non-autogenerated DDL in spirit.
    """
    op.rename_table(_OLD_NAME, _NEW_NAME)


def downgrade() -> None:
    """Downgrade schema."""
    op.rename_table(_NEW_NAME, _OLD_NAME)
