"""add_ticket_replies

Revision ID: 9132a68b73c8
Revises: 37c89e98a86f
Create Date: 2026-09-04 20:36:39.490962

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9132a68b73c8"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "37c89e98a86f"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Autogenerate's raw diff also proposed dropping and (on downgrade)
# re-creating `audit_log_default` and five indexes
# (`ix_account_lifecycle_audit_log_occurred_at`, `ix_admin_audit_log_occurred_at`,
# `ix_audit_log_occurred_at_actor_id_event`, `ix_auth_audit_log_occurred_at`,
# `ix_profile_audit_log_timestamp`, `ix_users_display_name_trgm`,
# `ix_users_email_trgm`) - all created via hand-written `op.execute()` DDL in
# prior migrations with no matching SQLAlchemy construct for autogenerate to
# compare against, so it saw them as "not in the model" and proposed removing
# them. None of this is in this story's scope; stripped from both
# `upgrade()`/`downgrade()` below, the same precedent
# `37c89e98a86f_add_support_tickets.py` and `2c77dd65027b_...py` already set.

# `attachments.ticket_reply_id`'s FK needs an explicit name: autogenerate
# left it unnamed (`create_foreign_key(None, ...)`), which only works because
# no `naming_convention` is registered on `Base.metadata`
# (app/db/base.py) - PostgreSQL's own default constraint-naming convention
# is used explicitly here so `downgrade()` can name it back.
_ATTACHMENTS_TICKET_REPLY_ID_FK = "attachments_ticket_reply_id_fkey"

# CREATE POLICY/ENABLE/FORCE ROW LEVEL SECURITY have no SQLAlchemy construct
# and are not reached by the Rewriter in migrations/env.py - hand-written
# op.execute() DDL, per AGENTS.md section 4. ENABLE/FORCE/DISABLE ROW LEVEL
# SECURITY are idempotent at the SQL level (rerunning is a no-op); only
# CREATE POLICY errors on a name that already exists, so only it needs the
# sa.inspect(op.get_bind())-style guard below (via pg_policies, since
# SQLAlchemy's Inspector has no policy introspection).
_ENABLE_RLS = "ALTER TABLE ticket_replies ENABLE ROW LEVEL SECURITY"
_FORCE_RLS = "ALTER TABLE ticket_replies FORCE ROW LEVEL SECURITY"
_DISABLE_RLS = "ALTER TABLE ticket_replies DISABLE ROW LEVEL SECURITY"
_CREATE_POLICY_READ = """
CREATE POLICY ticket_replies_read ON ticket_replies
  FOR SELECT
  USING (visibility = 'public' OR current_setting('app.actor_kind', true) = 'agent')
"""
_CREATE_POLICY_WRITE = """
CREATE POLICY ticket_replies_write ON ticket_replies
  FOR INSERT
  WITH CHECK (visibility = 'public' OR current_setting('app.actor_kind', true) = 'agent')
"""
_DROP_POLICY_READ = "DROP POLICY IF EXISTS ticket_replies_read ON ticket_replies"
_DROP_POLICY_WRITE = "DROP POLICY IF EXISTS ticket_replies_write ON ticket_replies"


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "ticket_replies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("author_kind", sa.String(length=20), nullable=False),
        sa.Column("body", sa.String(length=5000), nullable=False),
        sa.Column("visibility", sa.String(length=20), server_default="public", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visibility = 'public' OR author_kind = 'agent'",
            name="ck_ticket_replies_visibility_agent_only",
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"]),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        "ix_ticket_replies_ticket_id_created_at_id",
        "ticket_replies",
        ["ticket_id", "created_at", "id"],
        unique=False,
        if_not_exists=True,
    )
    # The Rewriter in migrations/env.py only reaches autogenerated
    # Create/DropTableOp and Create/DropIndexOp; add_column/create_foreign_key
    # need their own guard so upgrade/downgrade/upgrade cycles stay
    # idempotent, matching 2c77dd65027b's add_column guard pattern.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    ticket_columns = {c["name"] for c in inspector.get_columns("tickets")}
    if "first_response_at" not in ticket_columns:
        op.add_column(
            "tickets", sa.Column("first_response_at", sa.DateTime(timezone=True), nullable=True)
        )
    attachment_columns = {c["name"] for c in inspector.get_columns("attachments")}
    if "ticket_reply_id" not in attachment_columns:
        op.add_column("attachments", sa.Column("ticket_reply_id", sa.Uuid(), nullable=True))
    # Plain (non-CONCURRENTLY) index: US-4.1 shipped attachment binding
    # without an upload endpoint, so `attachments` has no production write
    # path populating it yet - AGENTS.md section 4's CONCURRENTLY hazard
    # applies to an already-populated table, not this one (DR-2, carried
    # finding).
    op.create_index(
        op.f("ix_attachments_ticket_reply_id"),
        "attachments",
        ["ticket_reply_id"],
        unique=False,
        if_not_exists=True,
    )
    attachment_fks = {fk["name"] for fk in inspector.get_foreign_keys("attachments")}
    if _ATTACHMENTS_TICKET_REPLY_ID_FK not in attachment_fks:
        op.create_foreign_key(
            _ATTACHMENTS_TICKET_REPLY_ID_FK,
            "attachments",
            "ticket_replies",
            ["ticket_reply_id"],
            ["id"],
        )

    op.execute(_ENABLE_RLS)
    op.execute(_FORCE_RLS)
    existing_policies = {
        row[0]
        for row in bind.execute(
            sa.text("SELECT policyname FROM pg_policies WHERE tablename = 'ticket_replies'")
        )
    }
    if "ticket_replies_read" not in existing_policies:
        op.execute(_CREATE_POLICY_READ)
    if "ticket_replies_write" not in existing_policies:
        op.execute(_CREATE_POLICY_WRITE)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(_DROP_POLICY_WRITE)
    op.execute(_DROP_POLICY_READ)
    op.execute(_DISABLE_RLS)

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    attachment_fks = {fk["name"] for fk in inspector.get_foreign_keys("attachments")}
    if _ATTACHMENTS_TICKET_REPLY_ID_FK in attachment_fks:
        op.drop_constraint(_ATTACHMENTS_TICKET_REPLY_ID_FK, "attachments", type_="foreignkey")
    op.drop_index(op.f("ix_attachments_ticket_reply_id"), table_name="attachments", if_exists=True)
    attachment_columns = {c["name"] for c in inspector.get_columns("attachments")}
    if "ticket_reply_id" in attachment_columns:
        op.drop_column("attachments", "ticket_reply_id")
    ticket_columns = {c["name"] for c in inspector.get_columns("tickets")}
    if "first_response_at" in ticket_columns:
        op.drop_column("tickets", "first_response_at")
    op.drop_index(
        "ix_ticket_replies_ticket_id_created_at_id", table_name="ticket_replies", if_exists=True
    )
    op.drop_table("ticket_replies", if_exists=True)
