"""add_logout_revocation_columns

Revision ID: 9f9d9263bdfc
Revises: 1cdc08e88be9
Create Date: 2026-08-31 22:23:02.016432

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f9d9263bdfc"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "1cdc08e88be9"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # The Rewriter in migrations/env.py only reaches autogenerated
    # Create/DropTableOp and Create/DropIndexOp; add_column/drop_column need
    # their own guard so upgrade/downgrade/upgrade cycles stay idempotent.
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    auth_audit_log_columns = {column["name"] for column in inspector.get_columns("auth_audit_log")}
    if "scope" not in auth_audit_log_columns:
        op.add_column("auth_audit_log", sa.Column("scope", sa.String(length=32), nullable=True))

    refresh_tokens_columns = {column["name"] for column in inspector.get_columns("refresh_tokens")}
    if "revoked_at" not in refresh_tokens_columns:
        op.add_column(
            "refresh_tokens", sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True)
        )

    op.create_index(
        "ix_refresh_tokens_family_id",
        "refresh_tokens",
        ["family_id"],
        unique=False,
        if_not_exists=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_refresh_tokens_family_id", table_name="refresh_tokens", if_exists=True)

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    refresh_tokens_columns = {column["name"] for column in inspector.get_columns("refresh_tokens")}
    if "revoked_at" in refresh_tokens_columns:
        op.drop_column("refresh_tokens", "revoked_at")

    auth_audit_log_columns = {column["name"] for column in inspector.get_columns("auth_audit_log")}
    if "scope" in auth_audit_log_columns:
        op.drop_column("auth_audit_log", "scope")
