"""add_refresh_rotation_columns

Revision ID: c8eeaa6b5ff6
Revises: 9f9d9263bdfc
Create Date: 2026-09-01 10:10:37.515996

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8eeaa6b5ff6"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "9f9d9263bdfc"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # The Rewriter in migrations/env.py only reaches autogenerated
    # Create/DropTableOp and Create/DropIndexOp; add_column/drop_column need
    # their own guard so upgrade/downgrade/upgrade cycles stay idempotent.
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    auth_audit_log_columns = {column["name"] for column in inspector.get_columns("auth_audit_log")}
    if "severity" not in auth_audit_log_columns:
        op.add_column("auth_audit_log", sa.Column("severity", sa.String(length=16), nullable=True))

    refresh_tokens_columns = {column["name"] for column in inspector.get_columns("refresh_tokens")}
    if "consumed_at" not in refresh_tokens_columns:
        op.add_column(
            "refresh_tokens", sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True)
        )
    if "last_used_at" not in refresh_tokens_columns:
        op.add_column(
            "refresh_tokens", sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True)
        )
    if "ip" not in refresh_tokens_columns:
        op.add_column("refresh_tokens", sa.Column("ip", sa.String(length=45), nullable=True))
    if "user_agent" not in refresh_tokens_columns:
        op.add_column("refresh_tokens", sa.Column("user_agent", sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    refresh_tokens_columns = {column["name"] for column in inspector.get_columns("refresh_tokens")}
    if "user_agent" in refresh_tokens_columns:
        op.drop_column("refresh_tokens", "user_agent")
    if "ip" in refresh_tokens_columns:
        op.drop_column("refresh_tokens", "ip")
    if "last_used_at" in refresh_tokens_columns:
        op.drop_column("refresh_tokens", "last_used_at")
    if "consumed_at" in refresh_tokens_columns:
        op.drop_column("refresh_tokens", "consumed_at")

    auth_audit_log_columns = {column["name"] for column in inspector.get_columns("auth_audit_log")}
    if "severity" in auth_audit_log_columns:
        op.drop_column("auth_audit_log", "severity")
