"""add_mfa_columns_and_recovery_codes

Revision ID: cef55228a927
Revises: d7585b660cd7
Create Date: 2026-09-01 23:03:40.048876

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cef55228a927"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "d7585b660cd7"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "mfa_recovery_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_mfa_recovery_codes_user_id"),
        "mfa_recovery_codes",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )

    # The Rewriter in migrations/env.py only reaches autogenerated
    # Create/DropTableOp and Create/DropIndexOp; add_column/drop_column need
    # their own guard so upgrade/downgrade/upgrade cycles stay idempotent
    # (matches 2c77dd65027b's pattern).
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    user_role_columns = {column["name"] for column in inspector.get_columns("user_roles")}
    if "granted_at" not in user_role_columns:
        op.add_column(
            "user_roles",
            sa.Column(
                "granted_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )

    user_columns = {column["name"] for column in inspector.get_columns("users")}
    if "mfa_enabled" not in user_columns:
        op.add_column(
            "users",
            sa.Column("mfa_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        )
    if "mfa_secret_encrypted" not in user_columns:
        op.add_column("users", sa.Column("mfa_secret_encrypted", sa.LargeBinary(), nullable=True))
    if "mfa_activated_at" not in user_columns:
        op.add_column(
            "users", sa.Column("mfa_activated_at", sa.DateTime(timezone=True), nullable=True)
        )
    if "mfa_reenrollment_required" not in user_columns:
        op.add_column(
            "users",
            sa.Column(
                "mfa_reenrollment_required",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            ),
        )


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    user_columns = {column["name"] for column in inspector.get_columns("users")}
    if "mfa_reenrollment_required" in user_columns:
        op.drop_column("users", "mfa_reenrollment_required")
    if "mfa_activated_at" in user_columns:
        op.drop_column("users", "mfa_activated_at")
    if "mfa_secret_encrypted" in user_columns:
        op.drop_column("users", "mfa_secret_encrypted")
    if "mfa_enabled" in user_columns:
        op.drop_column("users", "mfa_enabled")

    user_role_columns = {column["name"] for column in inspector.get_columns("user_roles")}
    if "granted_at" in user_role_columns:
        op.drop_column("user_roles", "granted_at")

    op.drop_index(
        op.f("ix_mfa_recovery_codes_user_id"), table_name="mfa_recovery_codes", if_exists=True
    )
    op.drop_table("mfa_recovery_codes", if_exists=True)
