"""add_admin_audit_log

Revision ID: d7585b660cd7
Revises: e50fbe8161fc
Create Date: 2026-09-01 20:20:28.850403

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7585b660cd7"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "e50fbe8161fc"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("old_roles", postgresql.ARRAY(sa.String(length=32)), nullable=True),
        sa.Column("new_roles", postgresql.ARRAY(sa.String(length=32)), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_admin_audit_log_actor_id"),
        "admin_audit_log",
        ["actor_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_admin_audit_log_target_id"),
        "admin_audit_log",
        ["target_id"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_admin_audit_log_target_id"), table_name="admin_audit_log", if_exists=True
    )
    op.drop_index(op.f("ix_admin_audit_log_actor_id"), table_name="admin_audit_log", if_exists=True)
    op.drop_table("admin_audit_log", if_exists=True)
    # ### end Alembic commands ###
