"""add_roles_and_permissions

Revision ID: e50fbe8161fc
Revises: 9a4776e19934
Create Date: 2026-09-01 20:16:09.755540

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e50fbe8161fc"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "9a4776e19934"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope"),
        if_not_exists=True,
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        if_not_exists=True,
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
        if_not_exists=True,
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False, if_not_exists=True
    )
    # ### end Alembic commands ###

    # Seed data: the fixed role/permission catalogue (spec Background) and
    # the role-to-scope mapping resolved 2026-09-01 (minimal per-persona,
    # docs/impact-analysis/US-3.2-impact-analysis.md). ON CONFLICT DO
    # NOTHING makes this idempotent across upgrade/downgrade/upgrade -
    # required since the Rewriter's if_not_exists/if_exists only reaches
    # autogenerated table/index ops, never hand-written data statements
    # (AGENTS.md SS4 Migrations).
    op.execute(
        """
        INSERT INTO roles (id, name) VALUES
            ('11111111-1111-1111-1111-111111111111', 'customer'),
            ('22222222-2222-2222-2222-222222222222', 'support_agent'),
            ('33333333-3333-3333-3333-333333333333', 'admin'),
            ('44444444-4444-4444-4444-444444444444', 'auditor')
        ON CONFLICT (name) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO permissions (id, scope) VALUES
            ('a1111111-1111-1111-1111-111111111111', 'users:read'),
            ('a2222222-2222-2222-2222-222222222222', 'users:write'),
            ('a3333333-3333-3333-3333-333333333333', 'roles:write'),
            ('a4444444-4444-4444-4444-444444444444', 'audit:read'),
            ('a5555555-5555-5555-5555-555555555555', 'tickets:read'),
            ('a6666666-6666-6666-6666-666666666666', 'tickets:write')
        ON CONFLICT (scope) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM roles r, permissions p
        WHERE (r.name = 'support_agent' AND p.scope IN ('tickets:read', 'tickets:write'))
           OR (r.name = 'auditor' AND p.scope = 'audit:read')
           OR (r.name = 'admin')
        ON CONFLICT (role_id, permission_id) DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles", if_exists=True)
    op.drop_table("user_roles", if_exists=True)
    op.drop_table("role_permissions", if_exists=True)
    op.drop_table("roles", if_exists=True)
    op.drop_table("permissions", if_exists=True)
    # ### end Alembic commands ###
